// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFAvhSUr5M1AfMwSaSEdpJM_eSev-0vPI',
    appId: '1:428884740566:web:bf9a4697bf5f95edd23c77',
    messagingSenderId: '428884740566',
    projectId: 'user-app-9b62b',
    authDomain: 'user-app-9b62b.firebaseapp.com',
    storageBucket: 'user-app-9b62b.appspot.com',
    measurementId: 'G-16RZ6ETM0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhIr-KTRlcE8LPC1JTDP-HzamraJ-heBQ',
    appId: '1:428884740566:android:6acf1a8695e45f27d23c77',
    messagingSenderId: '428884740566',
    projectId: 'user-app-9b62b',
    storageBucket: 'user-app-9b62b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOYq1ZOM-zThGsczIZ2Fc7-dllO6pgHIc',
    appId: '1:428884740566:ios:ee83f52cc5a96ce5d23c77',
    messagingSenderId: '428884740566',
    projectId: 'user-app-9b62b',
    storageBucket: 'user-app-9b62b.appspot.com',
    iosBundleId: 'com.example.userApp',
  );
}
